#pragma once
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimatedVisuals
{
	struct LottieLogo1 : winrt::implements<LottieLogo1, winrt::Microsoft::UI::Xaml::Controls::IAnimatedVisualSource>
	{
		winrt::Microsoft::UI::Xaml::Controls::IAnimatedVisual TryCreateAnimatedVisual(
			winrt::Windows::UI::Composition::Compositor const& compositor,
			winrt::Windows::Foundation::IInspectable& diagnostics);
	};
}